name: 'duck_db_test'
version: '0.1'
profile: 'duckdb'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["docs"]


log-path: "logs"

clean-targets:
  - "target"
  - "logs"

sources:
  duck_db_test:

models:
  +materialized: table
  duck_db_test:
